remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Proyecto web, git y Github

nombres: Andrés Camilo Quintana Montoya
submodulo: Introducción a la Programación
periodo: 2023-2